sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success:
- travis-after-all && npm run semantic-release
